# Generated by Django 4.2.2 on 2023-06-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_remove_etudiant_admin_remove_etudiant_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='username',
            field=models.CharField(default=0, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='matricule',
            field=models.CharField(max_length=50),
        ),
    ]
