# Generated by Django 4.2.2 on 2023-06-23 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etudiant',
            old_name='prénoms',
            new_name='prenom',
        ),
    ]
