# Generated by Django 4.2.2 on 2023-06-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_remove_etudiant_email_remove_etudiant_nom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.CharField(max_length=4)),
            ],
        ),
        migrations.RenameField(
            model_name='etudiant',
            old_name='telephone',
            new_name='Telephone',
        ),
    ]
