# Generated by Django 4.2.2 on 2023-06-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmploiDuTemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_etude', models.CharField(max_length=100)),
                ('numero_semaine', models.IntegerField()),
                ('cours_lundi', models.CharField(max_length=100)),
                ('professeur_lundi', models.CharField(max_length=100)),
                ('horaire_lundi', models.CharField(max_length=100)),
                ('salle_lundi', models.CharField(max_length=100)),
                ('materiels_lundi', models.CharField(max_length=100)),
                ('infos_lundi', models.CharField(max_length=100)),
                ('cours_Mardi', models.CharField(max_length=100)),
                ('professeur_Mardi', models.CharField(max_length=100)),
                ('horaire_Mardi', models.CharField(max_length=100)),
                ('salle_Mardi', models.CharField(max_length=100)),
                ('materiels_Mardi', models.CharField(max_length=100)),
                ('infos_Mardi', models.CharField(max_length=100)),
                ('cours_Mercredi', models.CharField(max_length=100)),
                ('professeur_Mercredi', models.CharField(max_length=100)),
                ('horaire_Mercredi', models.CharField(max_length=100)),
                ('salle_Mercredi', models.CharField(max_length=100)),
                ('materiels_Mercredi', models.CharField(max_length=100)),
                ('infos_Mercredi', models.CharField(max_length=100)),
                ('cours_Jeudi', models.CharField(max_length=100)),
                ('professeur_Jeudi', models.CharField(max_length=100)),
                ('horaire_Jeudi', models.CharField(max_length=100)),
                ('salle_Jeudi', models.CharField(max_length=100)),
                ('materiels_Jeudi', models.CharField(max_length=100)),
                ('infos_Jeudi', models.CharField(max_length=100)),
                ('cours_Vendredi', models.CharField(max_length=100)),
                ('professeur_Vendredi', models.CharField(max_length=100)),
                ('horaire_Vendredi', models.CharField(max_length=100)),
                ('salle_Vendredi', models.CharField(max_length=100)),
                ('materiels_Vendredi', models.CharField(max_length=100)),
                ('infos_Vendedi', models.CharField(max_length=100)),
                ('cours_Samedi', models.CharField(max_length=100)),
                ('professeur_Samedi', models.CharField(max_length=100)),
                ('horaire_Samedi', models.CharField(max_length=100)),
                ('salle_Samedi', models.CharField(max_length=100)),
                ('materiels_Samedi', models.CharField(max_length=100)),
                ('infos_Samedi', models.CharField(max_length=100)),
            ],
        ),
    ]
