# Generated by Django 4.2.2 on 2023-06-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploiTemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialite', models.CharField(max_length=100)),
                ('niveau_etude', models.CharField(max_length=100)),
                ('semaine', models.CharField(max_length=100)),
                ('jour', models.CharField(max_length=100)),
                ('intitule_cours', models.CharField(max_length=100)),
                ('nom_professeur', models.CharField(max_length=100)),
                ('materiel_necessaire', models.CharField(max_length=100)),
                ('creneau_horaire', models.CharField(max_length=100)),
                ('infos_supplementaires', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='EmploiDuTemps',
        ),
    ]
