# Generated by Django 3.2.19 on 2023-07-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='account_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=63)),
                ('email', models.CharField(max_length=63)),
                ('num_id', models.IntegerField()),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
