# Generated by Django 3.2.19 on 2023-07-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_account_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_request',
            name='password',
            field=models.CharField(default='my password', max_length=63),
        ),
    ]
