# Generated by Django 3.2.19 on 2023-06-23 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmploiDuTemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrip', models.TextField()),
                ('date_publication', models.DateTimeField(blank=True, null=True)),
                ('fil', models.CharField(default='ma_filière', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vendredi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_7_8', models.CharField(max_length=50)),
                ('v_8_9', models.CharField(max_length=50)),
                ('v_9_10', models.CharField(max_length=50)),
                ('v_10_11', models.CharField(max_length=50)),
                ('v_11_12', models.CharField(max_length=50)),
                ('v_12_13', models.CharField(max_length=50)),
                ('v_13_14', models.CharField(max_length=50)),
                ('v_14_15', models.CharField(max_length=50)),
                ('v_15_16', models.CharField(max_length=50)),
                ('v_16_17', models.CharField(max_length=50)),
                ('v_17_18', models.CharField(max_length=50)),
                ('v_18_19', models.CharField(max_length=50)),
                ('v_emploi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.emploidutemps')),
            ],
        ),
        migrations.CreateModel(
            name='Samedi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_7_8', models.CharField(max_length=50)),
                ('s_8_9', models.CharField(max_length=50)),
                ('s_9_10', models.CharField(max_length=50)),
                ('s_10_11', models.CharField(max_length=50)),
                ('s_11_12', models.CharField(max_length=50)),
                ('s_12_13', models.CharField(max_length=50)),
                ('s_13_14', models.CharField(max_length=50)),
                ('s_14_15', models.CharField(max_length=50)),
                ('s_15_16', models.CharField(max_length=50)),
                ('s_16_17', models.CharField(max_length=50)),
                ('s_17_18', models.CharField(max_length=50)),
                ('s_18_19', models.CharField(max_length=50)),
                ('s_emploi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.emploidutemps')),
            ],
        ),
        migrations.CreateModel(
            name='Mercredi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('me_7_8', models.CharField(max_length=50)),
                ('me_8_9', models.CharField(max_length=50)),
                ('me_9_10', models.CharField(max_length=50)),
                ('me_10_11', models.CharField(max_length=50)),
                ('me_11_12', models.CharField(max_length=50)),
                ('me_12_13', models.CharField(max_length=50)),
                ('me_13_14', models.CharField(max_length=50)),
                ('me_14_15', models.CharField(max_length=50)),
                ('me_15_16', models.CharField(max_length=50)),
                ('me_16_17', models.CharField(max_length=50)),
                ('me_17_18', models.CharField(max_length=50)),
                ('me_18_19', models.CharField(max_length=50)),
                ('me_emploi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.emploidutemps')),
            ],
        ),
        migrations.CreateModel(
            name='Mardi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_7_8', models.CharField(max_length=50)),
                ('m_8_9', models.CharField(max_length=50)),
                ('m_9_10', models.CharField(max_length=50)),
                ('m_10_11', models.CharField(max_length=50)),
                ('m_11_12', models.CharField(max_length=50)),
                ('m_12_13', models.CharField(max_length=50)),
                ('m_13_14', models.CharField(max_length=50)),
                ('m_14_15', models.CharField(max_length=50)),
                ('m_15_16', models.CharField(max_length=50)),
                ('m_16_17', models.CharField(max_length=50)),
                ('m_17_18', models.CharField(max_length=50)),
                ('m_18_19', models.CharField(max_length=50)),
                ('m_emploi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.emploidutemps')),
            ],
        ),
        migrations.CreateModel(
            name='Lundi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_7_8', models.CharField(max_length=50)),
                ('l_8_9', models.CharField(max_length=50)),
                ('l_9_10', models.CharField(max_length=50)),
                ('l_10_11', models.CharField(max_length=50)),
                ('l_11_12', models.CharField(max_length=50)),
                ('l_12_13', models.CharField(max_length=50)),
                ('l_13_14', models.CharField(max_length=50)),
                ('l_14_15', models.CharField(max_length=50)),
                ('l_15_16', models.CharField(max_length=50)),
                ('l_16_17', models.CharField(max_length=50)),
                ('l_17_18', models.CharField(max_length=50)),
                ('l_18_19', models.CharField(max_length=50)),
                ('l_emploi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.emploidutemps')),
            ],
        ),
        migrations.CreateModel(
            name='Jeudi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('j_7_8', models.CharField(max_length=50)),
                ('j_8_9', models.CharField(max_length=50)),
                ('j_9_10', models.CharField(max_length=50)),
                ('j_10_11', models.CharField(max_length=50)),
                ('j_11_12', models.CharField(max_length=50)),
                ('j_12_13', models.CharField(max_length=50)),
                ('j_13_14', models.CharField(max_length=50)),
                ('j_14_15', models.CharField(max_length=50)),
                ('j_15_16', models.CharField(max_length=50)),
                ('j_16_17', models.CharField(max_length=50)),
                ('j_17_18', models.CharField(max_length=50)),
                ('j_18_19', models.CharField(max_length=50)),
                ('j_emploi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.emploidutemps')),
            ],
        ),
    ]
