# Generated by Django 3.2.19 on 2023-06-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lundi',
            name='l_emploi',
        ),
        migrations.RemoveField(
            model_name='mardi',
            name='m_emploi',
        ),
        migrations.RemoveField(
            model_name='mercredi',
            name='me_emploi',
        ),
        migrations.RemoveField(
            model_name='samedi',
            name='s_emploi',
        ),
        migrations.RemoveField(
            model_name='vendredi',
            name='v_emploi',
        ),
        migrations.RemoveField(
            model_name='emploidutemps',
            name='date_publication',
        ),
        migrations.RemoveField(
            model_name='emploidutemps',
            name='descrip',
        ),
        migrations.RemoveField(
            model_name='emploidutemps',
            name='fil',
        ),
        migrations.AddField(
            model_name='emploidutemps',
            name='emploi',
            field=models.JSONField(default={'valeur': 'par_defaut'}),
        ),
        migrations.DeleteModel(
            name='Jeudi',
        ),
        migrations.DeleteModel(
            name='Lundi',
        ),
        migrations.DeleteModel(
            name='Mardi',
        ),
        migrations.DeleteModel(
            name='Mercredi',
        ),
        migrations.DeleteModel(
            name='Samedi',
        ),
        migrations.DeleteModel(
            name='Vendredi',
        ),
    ]
