# Generated by Django 3.2.19 on 2023-06-28 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20230628_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emploidutemps',
            old_name='emploi',
            new_name='emploi_data',
        ),
    ]
