# Generated by Django 3.2.19 on 2023-06-30 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_auto_20230630_1726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminuser',
            options={'verbose_name_plural': 'Admin Users'},
        ),
    ]
