# Generated by Django 3.2.19 on 2023-06-30 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_alter_adminuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
