# Generated by Django 3.2.19 on 2023-06-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0012_remove_adminuser_a_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='a_email',
            field=models.EmailField(default='votreemail@gmail.com', max_length=254, unique=True),
        ),
    ]
