# Generated by Django 3.2.19 on 2023-06-30 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0015_alter_adminuser_a_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
