# Generated by Django 3.2.19 on 2023-07-01 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0016_alter_adminuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='studentuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='AdminUser',
        ),
        migrations.DeleteModel(
            name='StudentUser',
        ),
    ]
