# Generated by Django 3.2.19 on 2023-07-01 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0020_auto_20230701_1951'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
