# Generated by Django 4.2.2 on 2023-06-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('bithdate', models.DateTimeField()),
                ('email', models.EmailField(max_length=254)),
                ('passwords', models.CharField(max_length=100)),
            ],
        ),
    ]
